from . import maquina
from . import cuadre_caja
from . import bill_drop
from . import devolucion
from . import marca
from . import otros_pagos
from . import res_partner
from . import res_company
from . import res_config_settings
from . import cobro_tc
from . import sobrante_faltante
from . import comision_marca