from . import maquina
from . import cuadre_caja
from . import bill_drop
from . import devolucion
from . import marca
from . import otros_pagos
from . import res_partner
from . import res_company
from . import res_config_settings
from . import cobro_tc
from . import sobrante_faltante
from . import comision_marca
from . import lender_deposit
from . import encargado_caja
from . import mesa
from . import apuesta_mesa
from . import tipo_error_pago
from . import tipo_premio
from . import rifas_premios_maquina